# -*- coding: utf-8 -*-
"""maltaekniverkefni4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrRUsQ2TUgKsVbWKQmc5e4LHLqR3ESIg

2) Try the models on the problems they are meant to solve (for example translating
from Icelandic to German using this model or answering questions with this
model). Try each model at least five times. Discuss the results. Do you see errors
in the output? Try to explain what might cause that.
"""

from transformers import pipeline

qa_model = pipeline("question-answering", model="vesteinn/XLMr-ENIS-QA-Is")

qa_tests = [
    {"context": "Elon Musk er forstjóri Tesla og einn af stofnendum SpaceX.",
     "question": "Hver er forstjóri Tesla?"},
    {"context": "Albert Einstein fann upp afstæðiskenninguna.",
     "question": "Hver fann upp afstæðiskenninguna?"},
    {"context": "Tesla var stofnað af Martin Eberhard og Marc Tarpenning.",
     "question": "Hver stofnaði Tesla?"},
    {"context": "Ísland er land í norðri og höfuðborg þess er Reykjavík.",
     "question": "Hver er höfuðborg Íslands?"},
    {"context": "Jörðin er reikistjarna sem snýst um sólina.",
     "question": "Hvaða reikistjarna snýst um sólina?"}
]


for test in qa_tests:
    result = qa_model(question=test["question"], context=test["context"])
    print(f"Q: {test['question']}")
    print(f"A: {result['answer']} (Score: {result['score']:.2f})\n")

ner_model = pipeline("ner", model="Andrey1989/mbert-finetuned-ner")

ner_sentences = [
    "Bill Gates stofnaði Microsoft í Bandaríkjunum.",
    "Angela Merkel var kanslari Þýskalands.",
    "Ísland er land í Evrópu og Reykjavík er höfuðborg þess.",
    "Nikola Tesla var uppfinningamaður sem fæddist í Serbíu.",
    "Amazon er stórt tæknifyrirtæki sem stofnaði Jeff Bezos."
]

for sentence in ner_sentences:
    results = ner_model(sentence)
    print(f"\nSentence: {sentence}")
    for entity in results:
        print(f"{entity['word']} -> {entity['entity']} (Score: {entity['score']:.2f})")

translator = pipeline("translation", model="facebook/m2m100_418M")

translations = [
    ("Ég elska að læra ný tungumál.", "is", "en"),
    ("Reykjavík er falleg borg.", "is", "fr"),
    ("Við borðuðum kvöldmat klukkan átta.", "is", "de"),
    ("Hvernig gengur þér í dag?", "is", "es"),
    ("Veðrið er kalt á Íslandi á veturna.", "is", "zh")

for text, src, tgt in translations:
    translated_text = translator(text, src_lang=src, tgt_lang=tgt)
    print(f"Original ({src}): {text}")
    print(f"Translated ({tgt}): {translated_text[0]['translation_text']}\n")

"""The models worked well, but some issues came up.

For question answering, it correctly found answers like "Elon Musk" and "Albert Einstein" but it struggled with the question like the one about the solar system. In that questions it had low confidence score. This could be because the Icelandic phrasing doesnt match its training data perfectly.

For ner it correctly identified names like Bill Gates and Jeff Bezos, but sometimes split words into parts. Not sure why it does that.

For translation, simple sentences were translated well I think, it's hard to tell if it did a good jobb. But I could image there would be some errors because Icelandic isn’t as common in the training data for those languages.

In general, the models did a good job, but struggled sometimes. More training in Icelandic would likely improve them.

#3) Make a very simple user interface for the model (it doesn’t have to be more complex than using the input() function in the command line or a notebook) where a user can write an appropriate input for the model and get a corresponding output. Show me an example of the functionality.
"""

from transformers import pipeline

qa_model = pipeline("question-answering", model="vesteinn/XLMr-ENIS-QA-Is")

# user interface
print("Question Answering Model (Icelandic-English)")
context = input("Enter the text context: ")
question = input("Enter your question: ")

result = qa_model(question=question, context=context)

print(f"\n Answer: {result['answer']} (Confidence: {result['score']:.2f})")

from transformers import pipeline

ner_model = pipeline("ner", model="Andrey1989/mbert-finetuned-ner")

# user interface
print("Named Entity Recognition Model")
text = input("Enter a sentence: ")

results = ner_model(text)

print("\n Recognized Entities:")
for entity in results:
    print(f"{entity['word']} -> {entity['entity']} (Confidence: {entity['score']:.2f})")

from transformers import pipeline

translator = pipeline("translation", model="facebook/m2m100_418M")

#user interface
print("Machine Translation Model")
text = input("Enter an Icelandic sentence to translate: ")
target_lang = input("Enter the target language (e.g., en, fr, de, es, zh): ")

translated_text = translator(text, src_lang="is", tgt_lang=target_lang)

print(f"\n Translation ({target_lang}): {translated_text[0]['translation_text']}")