# -*- coding: utf-8 -*-
"""homework5_tol025m

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iuxLcNjZUyRRx-iHK_su-LJ4poaX1bbz

##Dæmi 2
"""

import re

text = [
    "Elon Musk announced a new product launch at Tesla headquarters last Friday.",
    "The Prime Minister of Iceland Katrín Jakobsdóttir met with Joe Biden in Washington D.C.",
    "Apple Inc. revealed its latest iPhone model during the September 2024 keynote event.",
    "The concert featuring Beyoncé will take place in London on Saturday night.",
    "Harvard University offers a popular course on artificial intelligence.",
    "Tourists love visiting Gullfoss in Iceland.",
    "Microsoft acquired GitHub back in 2018.",
    "The World Health Organization released a report on global health trends.",
    "Cristiano Ronaldo scored two goals in Real Madrid's latest match against Barcelona.",
    "The new Marvel movie “Avengers: Secret Wars” will premiere in May 2025."
]

#regular expressions
person_pattern = re.compile(r'\b([A-Z][a-z]+(?:\s[A-Z][a-z]+)+)\b')
location_pattern = re.compile(r'\b(?:in|at|on|to)\s([A-Z][a-z]+(?:\s[A-Z][a-z]+)*)')
org_pattern = re.compile(r'\b(?:the\scompany\s)?([A-Z][a-zA-Z]+(?:\s[A-Z][a-zA-Z]+)*\s(?:University|Inc\.|Organization|Ltd|Institute|Company))')
date_pattern = re.compile(r'\b(?:on|in|by)?\s?(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|\b(January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4})\b')

#get entities from sentences
def extract_entities(sentences):
    results = []
    for sentence in sentences:
        people = person_pattern.findall(sentence)
        locations = location_pattern.findall(sentence)
        orgs = org_pattern.findall(sentence)
        dates = date_pattern.findall(sentence)

        flat_dates = [" ".join(filter(None, d)) for d in dates]

        results.append({
            "sentence": sentence,
            "people": people,
            "locations": locations,
            "organizations": orgs,
            "dates": flat_dates
        })
    return results

entities = extract_entities(text)

import pandas as pd
pd.DataFrame(entities)

"""#Dæmi 3a

"""

# First, install spaCy and download English model
!pip install -U spacy
!python -m spacy download en_core_web_sm

import spacy
import pandas as pd

# Load ner (spacy)
nlp = spacy.load("en_core_web_sm")

# same sample text
text = [
    "Elon Musk announced a new product launch at Tesla headquarters last Friday.",
    "The Prime Minister of Iceland Katrín Jakobsdóttir met with Joe Biden in Washington D.C.",
    "Apple Inc. revealed its latest iPhone model during the September 2024 keynote event.",
    "The concert featuring Beyoncé will take place in London on Saturday night.",
    "Harvard University offers a popular course on artificial intelligence.",
    "Tourists love visiting Gullfoss in Iceland.",
    "Microsoft acquired GitHub back in 2018.",
    "The World Health Organization released a report on global health trends.",
    "Cristiano Ronaldo scored two goals in Real Madrid's latest match against Barcelona.",
    "The new Marvel movie “Avengers: Secret Wars” will premiere in May 2025."
]

#Collect named entities
ner_results = []

for sentence in text:
    doc = nlp(sentence)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    ner_results.append({
        "sentence": sentence,
        "entities": entities
    })

# Display in table
df = pd.DataFrame(ner_results)
pd.set_option('display.max_colwidth', None)
df

"""##Dæmi 3b"""

import spacy
import pandas as pd
import re
import urllib.parse


nlp = spacy.load("en_core_web_sm")

text = [
    "Elon Musk announced a new product launch at Tesla headquarters last Friday.",
    "The Prime Minister of Iceland Katrín Jakobsdóttir met with Joe Biden in Washington D.C.",
    "Apple Inc. revealed its latest iPhone model during the September 2024 keynote event.",
    "The concert featuring Beyoncé will take place in London on Saturday night.",
    "Harvard University offers a popular course on artificial intelligence.",
    "Tourists love visiting Gullfoss and Thingvellir National Park in Iceland.",
    "Microsoft acquired GitHub back in 2018.",
    "The World Health Organization released a report on global health trends.",
    "Cristiano Ronaldo scored two goals in Real Madrid's latest match against Barcelona.",
    "The new Marvel movie “Avengers: Secret Wars” will premiere in May 2025."
]

# Base URL for Wikipedia
wikipedia_base_url = "https://en.wikipedia.org/wiki/"

# This function turns a named entity into a proper Wikipedia link
def create_wikipedia_link(entity_text):
    text = re.sub(r"[’'`]s", "", entity_text)
    text = text.strip(".,:;!?()\"“”‘’")
    text = text.replace(" ", "_")
    return wikipedia_base_url + urllib.parse.quote(text)

results = []

# Through each sentence and find named entities
for sentence in text:
    doc = nlp(sentence)
    entity_info = []

    for entity in doc.ents:
        entity_text = entity.text
        entity_label = entity.label_
        wikipedia_link = create_wikipedia_link(entity_text)
        entity_info.append((entity_text, entity_label, wikipedia_link))

    results.append({
        "sentence": sentence,
        "entities": entity_info
    })

df = pd.DataFrame(results)

pd.set_option("display.max_colwidth", None)
df

# rssults in readable way
print("Named Entities and Wikipedia Links:\n")

for item in results:
    print(f"📌 Sentence: {item['sentence']}")
    if item['entities']:
        for ent_text, ent_label, wiki_url in item['entities']:
            print(f"  - {ent_text} ({ent_label}) → {wiki_url}")
    else:
        print("  - No entities found.")
    print()

"""##Dæmi 4

"""

import re

# Your original text
text = [
    "Elon Musk announced a new product launch at Tesla headquarters last Friday.",
    "The Prime Minister of Iceland Katrín Jakobsdóttir met with Joe Biden in Washington D.C.",
    "Apple Inc. revealed its latest iPhone model during the September 2024 keynote event.",
    "The concert featuring Beyoncé will take place in London on Saturday night.",
    "Harvard University offers a popular course on artificial intelligence.",
    "Tourists love visiting Gullfoss and Thingvellir National Park in Iceland.",
    "Microsoft acquired GitHub back in 2018.",
    "The World Health Organization released a report on global health trends.",
    "Cristiano Ronaldo scored two goals in Real Madrid's latest match against Barcelona.",
    "The new Marvel movie “Avengers: Secret Wars” will premiere in May 2025."
]


relations = []

for sentence in text:
    relation_found = False
    match = re.search(r"(Elon Musk) .* (Tesla)", sentence)
    if match:
        relations.append((match.group(1), "CEO_of", match.group(2)))
        relation_found = True

    match = re.search(r"(Katrín Jakobsdóttir) met with (Joe Biden)", sentence)
    if match:
        relations.append((match.group(1), "met_with", match.group(2)))
        relation_found = True

    match = re.search(r"(Microsoft) acquired (GitHub)", sentence)
    if match:
        relations.append((match.group(1), "acquired", match.group(2)))
        relation_found = True

    match = re.search(r"(Harvard University).* in (.+?)\.", sentence)
    if match:
        relations.append((match.group(1), "located_in", match.group(2)))
        relation_found = True

    match = re.search(r"(Cristiano Ronaldo).* in (Real Madrid)", sentence)
    if match:
        relations.append((match.group(1), "plays_for", match.group(2)))
        relation_found = True

    if not relation_found:
        relations.append((sentence, "no_relation_found", "-"))

print("Extracted Relations:\n")
for triple in relations:
    subject, relation, obj = triple
    if relation != "no_relation_found":
        print(f"{subject} — {relation} — {obj}")
    else:
        print(f"no relation found in: \"{subject}\"")